name: Sync

on:
  schedule:
    # every 12 hour
    - cron: "0 */12 * * *"

  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@master
        with:
          ref: 2024
      - uses: oven-sh/setup-bun@main
        with:
          bun-version: latest
          bun-download-url: "https://github.com/oven-sh/bun/releases/latest/download/bun-linux-x64.zip"

      - run: bun i
      - run: bun run scripts/sync.ts
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

      - uses: stefanzweifel/git-auto-commit-action@master
        with:
          commit_author: Actions Bot <actions@github.com>
          skip_fetch: true
          branch: 2024
